config/routes.rb
Rails.application.routes.draw do
  root 'exchanges#index'
  get 'convert', to: 'exchanges#convert'

  get 'exchanges_btc/index', to: 'exchanges_btc#index'
  get 'convert_btc', to: 'exchanges_btc#convert'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exchanges_btc_controller.rb
class ExchangesBtcController < ApplicationController
  def index
  end

  def convert
    value = ExchangeBtcService.new(params[:source_currency], params[:target_currency], params[:amount]).perform
    render json: {"value": value}
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  def index
  end

  def convert
    value = ExchangeService.new(params[:source_currency], params[:target_currency], params[:amount]).perform
    render json: {"value": value}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchanges_btc_helper.rb
module ExchangesBtcHelper
  def source_currency_list
    [
      'BTC'
    ]
  end

end

app/helpers/exchanges_helper.rb
module ExchangesHelper

  def currency_list
    [
      'AUD', 'BGN', 'BRL', 'CAD', 'CHF', 'CNY', 'CZK', 'DKK', 'EUR', 'GBP',
      'HKD', 'HRK', 'HUF', 'IDR', 'ILS', 'INR', 'JPY', 'KRW', 'MXN',
      'MYR', 'NOK', 'NZD', 'PHP', 'PLN', 'RON', 'RUB', 'SEK', 'SGD',
      'THB', 'TRY', 'USD', 'ZAR'
    ]
  end
  
end

app/views/exchanges/_exchange_box.html.erb
<div class='exchange_box col-sm-12'>
  <div class='card'>

    <div class='card-block'>
      <%= form_tag('/convert', method: :get, id: 'exchange_form') do %>
        <div class='local_currency'>
          <div class='form-group'>
            <p class='title'>Moeda Local</p>
            <%= select_tag 'source_currency', options_for_select(currency_list, 'BRL'), class: 'form-control', id: 'source_currency' %>
          </div>

          <div class='form-group'>
            <input type='number' name='amount' id='amount' class='form-control' placeholder='Quantidade ($10)' step='any' required>
          </div>
        </div>

        <div class='form-group text-center'>
          <%= image_tag '/reverse.svg', class: 'btn img-fluid reverse-btn'%>
        </div>
                    
        <div class='destination_currency'>
          <div class='form-group'>
            <p class='title'>Moeda Pretendida</p>
            <%= select_tag 'target_currency', options_for_select(currency_list, 'USD'), class: 'form-control', id: 'target_currency'%>
          </div>
          <div class='form-group'>
            <input type='text' id='result' name='result' class='form-control' placeholder='Resultado' readonly>
          </div>
        </div>
        <div class="d-none">
          <button type='submit' class='btn btn-primary btn-exchange col-md-12'>CONVERTER</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/exchanges/index.html.erb
<div class="loader"></div>
<div class='container'>
  <div class='row main'>
    <div class='col-lg-3 offset-lg-1 col-md-10 offset-md-1 exchange_box'>
      <div class='row'>
          <div class='col-md-8 offset-md-2 text-sm-center'>
            <%= image_tag '/logo.png', class: 'img-fluid'%>
          </div>
      </div>

      <ul class="nav nav-tabs">
        <li class="nav-item">
          <%= link_to "Moedas", root_path, id:"currency", class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Criptomoedas", exchanges_btc_index_path, id:"cripto", class:"nav-link" %>
        </li>
      </ul>

      <div class='row'>
        <%= render 'exchange_box' %>
      </div>
    </div>

    <div class='col-lg-7 offset-lg-1 hidden-sm-down title-box'>
      <div class='row'>
        <h2 class='subtitle'><span class="contrast">Converta</span> facilmente suas <span class="contrast">Moedas</span></h2>
      </div>
                
      <div class='row'>
        <h3 class='subtitle'>Para qualquer moeda no <span class="contrast">Mundo!</span></h3>
      </div>
    </div>
  </div>
</div>

app/views/exchanges_btc/_exchange_btc_box.html.erb
<div class='exchange_box col-sm-12'>
  <div class='card'>

    <div class='card-block'>
      <%= form_tag('/convert_btc', method: :get, id: 'exchange_form') do %>
        <div class='local_currency'>
          <div class='form-group'>
            <p class='title'>Moeda Local</p>
            <%= select_tag 'source_currency', options_for_select(source_currency_list, 'BTC'), class: 'form-control', id: 'source_currency' %>
          </div>

          <div class='form-group'>
            <input type='number' name='amount' id='amount' class='form-control' placeholder='Quantidade' step='any' required>
          </div>
        </div>

        <div class='form-group text-center'>
          <%= image_tag '/reverse.svg', class: 'btn img-fluid reverse-btc-btn'%>
        </div>
                    
        <div class='destination_currency'>
          <div class='form-group'>
            <p class='title'>Moeda Pretendida</p>
            <%= select_tag 'target_currency', options_for_select(currency_list, 'BRL'), class: 'form-control', id: 'target_currency'%>
          </div>
          <div class='form-group'>
            <input type='text' id='result' name='result' class='form-control' placeholder='Resultado' readonly>
          </div>
        </div>
        <div class="d-none">
          <button type='submit' class='btn btn-primary btn-exchange-btc col-md-12'>CONVERTER</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/exchanges_btc/index.html.erb
<div class="loader"></div>
<div class='container'>
  <div class='row main'>
    <div class='col-lg-3 offset-lg-1 col-md-10 offset-md-1 exchange_box'>
      <div class='row'>
          <div class='col-md-8 offset-md-2 text-sm-center'>
            <%= image_tag '/logo.png', class: 'img-fluid'%>
          </div>
      </div>

      <ul class="nav nav-tabs">
        <li class="nav-item">
          <%= link_to "Moedas", root_path, id:"currency", class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Criptomoedas", exchanges_btc_index_path, id:"cripto", class:"nav-link active" %>
        </li>
      </ul>

      <div class='row'>
        <%= render 'exchange_btc_box' %>
      </div>
    </div>

    <div class='col-lg-7 offset-lg-1 hidden-sm-down title-box'>
      <div class='row'>
        <h2 class='subtitle'><span class="contrast">Converta</span> facilmente seus <span class="contrast">Bitcoins</span></h2>
      </div>
                
      <div class='row'>
        <h3 class='subtitle'>Para qualquer moeda no <span class="contrast">Mundo!</span></h3>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneBitExchange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag '/favicon.png' %>

  </head>

  <body class="back-1">
    <%= yield %>
  </body>
</html>